### PR TITLE
Better Benchmarking

### PR DESCRIPTION
**Pull request by reubenharry**
I wanted to make the speed benchmarking more automated. Here's how it works:

1. On the master branch, run `make set-bench`. This will run a multivariate Gaussian several times, and create a (gitignored) file saving info about the run and your machine. Because it's gitignored, it will just stay on your machine, even when you change branches.
2. Once you've made a change, on a new branch, run `make compare-bench`. This will run the same Gaussian, and if it's on average more than 2% slower than the existing benchmark, it will fail.

For example, I might attempt some refactoring of the code in the future, and if I do, I will follow the above. That way, I can be sure that the code is not significantly slower.

### CODE REVIEW

**Comment by JakobRobnik** [comment]
This is what I get if I run
make set-bench

make: *** No rule to make target 'set-bench'.  Stop.

What is the issue?

Jakob

**Comment by reubenharry** [comment]
@JakobRobnik  Sorry, I should have been clearer. `make set-bench` will only work once this PR is merged to the master branch. I generally don't merge branches immediately, since I want to give you a chance to look at them first. But if you merge this pull request, then `make set-bench` should work as intended on the master branch.

**Comment by JakobRobnik** [comment]
Sorry, thanks.
This is what I get:

ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --benchmark-autosave
  inifile: None
  rootdir: /home/jakob/Physics/MicroCanonicalHMC

**Comment by reubenharry** [comment]
Can you try doing `pip install -r requirements.txt`, and then rerunning? I think it's probably that you need to install `pytest-benchmark`

**Comment by JakobRobnik** [comment]
It works now, thanks!

**Pull request merged**
